version: "3.8"

networks:
  web:
    external: true
  internal:
    external: false

services:
  wordpress:
    labels:
      - traefik.enable=true
      - traefik.http.routers.${PROJECT}-http.entrypoints=web
      - traefik.http.routers.${PROJECT}-http.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.${PROJECT}-http.middlewares=${PROJECT}-https@docker
      - traefik.http.middlewares.${PROJECT}-https.redirectscheme.scheme=https
      - traefik.http.routers.${PROJECT}.entrypoints=websecure
      - traefik.http.routers.${PROJECT}.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.${PROJECT}.tls=true
      - traefik.http.routers.${PROJECT}.tls.certresolver=lets-encrypt
      - traefik.port=80
      - "traefik.http.middlewares.${PROJECT}-compress.compress=true"
      - "traefik.http.routers.${PROJECT}.middlewares=${PROJECT}-compress@docker"
    #      - traefik.http.middlewares.${PROJECT}-auth.basicauth.users=smallfish:$$apr1$$qKS5h3Ee$$ryblpf7DmJd5L6PKfcoMM1
    networks:
      - internal
      - web

  db:
    labels:
      - traefik.enable=false
    networks:
      - internal

  node:
    depends_on:
      - wordpress
    build:
      context: node
      dockerfile: Dockerfile
    volumes:
      - ./wp-content/themes/sardynkibiznesu-2.0/assets:/app/wp-content/themes/sardynkibiznesu-2.0/assets:rw
    labels:
      - traefik.enable=false
    networks:
      - internal
